# Generated by Django 5.2.1 on 2025-06-02 07:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="租户ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="租户名称")),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="租户标识符"
                    ),
                ),
                (
                    "subdomain",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="子域名"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="租户描述"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tenant_logos",
                        verbose_name="租户Logo",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="联系邮箱"),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="联系电话"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="地址"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="过期时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "租户",
                "verbose_name_plural": "租户",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TenantQuota",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_users",
                    models.IntegerField(default=10, verbose_name="最大用户数"),
                ),
                (
                    "max_api_keys",
                    models.IntegerField(default=5, verbose_name="最大API密钥数"),
                ),
                (
                    "max_api_requests_per_day",
                    models.IntegerField(
                        default=10000, verbose_name="每日最大API请求数"
                    ),
                ),
                (
                    "max_storage_gb",
                    models.IntegerField(default=5, verbose_name="最大存储空间(GB)"),
                ),
                (
                    "max_log_retention_days",
                    models.IntegerField(default=30, verbose_name="最大日志保留天数"),
                ),
                (
                    "max_notifications_per_day",
                    models.IntegerField(default=1000, verbose_name="每日最大通知数"),
                ),
                (
                    "current_user_count",
                    models.IntegerField(default=0, verbose_name="当前用户数"),
                ),
                (
                    "current_api_key_count",
                    models.IntegerField(default=0, verbose_name="当前API密钥数"),
                ),
                (
                    "current_storage_used_gb",
                    models.FloatField(
                        default=0.0, verbose_name="当前已使用存储空间(GB)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quota",
                        to="tenant_service.tenant",
                        verbose_name="租户",
                    ),
                ),
            ],
            options={
                "verbose_name": "租户配额",
                "verbose_name_plural": "租户配额",
            },
        ),
        migrations.CreateModel(
            name="TenantSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme_primary_color",
                    models.CharField(
                        default="#1976D2", max_length=20, verbose_name="主题主色"
                    ),
                ),
                (
                    "theme_secondary_color",
                    models.CharField(
                        default="#424242", max_length=20, verbose_name="主题辅色"
                    ),
                ),
                (
                    "enable_notifications",
                    models.BooleanField(default=True, verbose_name="启用通知"),
                ),
                (
                    "enable_api_keys",
                    models.BooleanField(default=True, verbose_name="启用API密钥"),
                ),
                (
                    "enable_two_factor_auth",
                    models.BooleanField(default=False, verbose_name="启用双因素认证"),
                ),
                (
                    "password_expiry_days",
                    models.IntegerField(default=90, verbose_name="密码过期天数"),
                ),
                (
                    "max_login_attempts",
                    models.IntegerField(default=5, verbose_name="最大登录尝试次数"),
                ),
                (
                    "session_timeout_minutes",
                    models.IntegerField(default=30, verbose_name="会话超时分钟数"),
                ),
                (
                    "default_notification_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="默认通知邮箱",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Asia/Shanghai", max_length=50, verbose_name="时区"
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        default="YYYY-MM-DD", max_length=20, verbose_name="日期格式"
                    ),
                ),
                (
                    "time_format",
                    models.CharField(
                        default="HH:mm:ss", max_length=20, verbose_name="时间格式"
                    ),
                ),
                (
                    "settings_json",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展设置"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="tenant_service.tenant",
                        verbose_name="租户",
                    ),
                ),
            ],
            options={
                "verbose_name": "租户设置",
                "verbose_name_plural": "租户设置",
            },
        ),
        migrations.CreateModel(
            name="TenantUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "所有者"),
                            ("admin", "管理员"),
                            ("member", "成员"),
                        ],
                        default="member",
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_users",
                        to="tenant_service.tenant",
                        verbose_name="租户",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "租户用户",
                "verbose_name_plural": "租户用户",
                "ordering": ["tenant", "role", "user"],
                "unique_together": {("tenant", "user")},
            },
        ),
    ]
