# Generated by Django 5.2.1 on 2025-06-04 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service", "0002_initial"),
        ("tenant_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "角色",
                "verbose_name_plural": "角色",
            },
        ),
        migrations.AlterField(
            model_name="permission",
            name="is_system",
            field=models.BooleanField(
                default=True,
                help_text="系统权限适用于所有租户，不关联特定租户",
                verbose_name="是否系统权限",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="is_tenant_level",
            field=models.BooleanField(
                default=False,
                help_text="租户级权限特定于某个租户，必须关联到特定租户",
                verbose_name="是否租户级权限",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="租户级权限必须关联租户，系统权限不关联租户",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permissions",
                to="tenant_service.tenant",
                verbose_name="所属租户",
            ),
        ),
    ]
