# Generated by Django 5.2.1 on 2025-06-24 01:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_service", "0003_alter_role_options_alter_permission_is_system_and_more"),
        ("tenant_service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="服务ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="服务代码"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="服务名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="服务描述"),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=True,
                        help_text="系统服务适用于所有租户，不关联特定租户",
                        verbose_name="是否系统服务",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="租户级服务必须关联租户，系统服务不关联租户",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="tenant_service.tenant",
                        verbose_name="所属租户",
                    ),
                ),
            ],
            options={
                "verbose_name": "服务",
                "verbose_name_plural": "服务",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="操作ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, verbose_name="操作代码")),
                ("name", models.CharField(max_length=100, verbose_name="操作名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="操作描述"),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=True,
                        help_text="系统操作适用于所有租户，不关联特定租户",
                        verbose_name="是否系统操作",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="租户级操作必须关联租户，系统操作不关联租户",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="tenant_service.tenant",
                        verbose_name="所属租户",
                    ),
                ),
            ],
            options={
                "verbose_name": "操作",
                "verbose_name_plural": "操作",
                "ordering": ["code"],
                "unique_together": {("code", "is_system"), ("code", "tenant")},
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="资源ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, verbose_name="资源代码")),
                ("name", models.CharField(max_length=100, verbose_name="资源名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="资源描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="auth_service.service",
                        verbose_name="所属服务",
                    ),
                ),
            ],
            options={
                "verbose_name": "资源",
                "verbose_name_plural": "资源",
                "ordering": ["service", "code"],
                "unique_together": {("service", "code")},
            },
        ),
    ]
